### ISSUE TITLE
API URI - Wrong Sign IN URL 

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-react-oauth#2]
Hello @FullStackkDev 

The SignIN/SignUP is not working. 

The URI used to communicate with the API is changed: 

- current SignIN URI: `http://localhost:5000/api/login`
- correct SignIN URI: `http://localhost:5000/api/users/login`

Same issue with the registration. 

Please take a look. Ty! 

*** *** ***

The expected URLs are listed below:

- REACT_APP_BACKEND_SERVER='http://localhost:5000/api/'
  - Format: PROTO + IP + PORT + (suffix) `/api/`
  - terminated in slash
- **SIGN_IN** is the `backend server` (above value) + `users/login`
- **SIGN_UP** is the `backend server` (above value) + `users/register`

*** *** *** ***

![image](https://user-images.githubusercontent.com/51070104/205096423-45751b9e-8776-4838-9f0a-170a28d48cd1.png)

**Comment by app-generator** [comment]
![image](https://user-images.githubusercontent.com/51070104/205096348-a4492ba8-f8bf-49e3-bff2-d1fecbc819e2.png)

**Comment by FullStackkDev** [comment]
@app-generator Here is the PR related to this issue: https://github.com/app-generator/sample-react-oauth/pull/3/files

**Comment by app-generator** [comment]
Validated. Closing.
Ty @FullStackkDev
